# Generated by Django 4.2 on 2023-12-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
    ]
